<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Slider wordpress generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Slider wordpress" />
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7">
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/fachada.jpg" alt="fachada" title="fachada" id="wows1_0"/></li>
<li><img src="data1/images/fachada02.jpg" alt="fachada-02" title="fachada-02" id="wows1_1"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="fachada"><img src="data1/tooltips/fachada.jpg" alt="fachada"/>1</a>
<a href="#" title="fachada-02"><img src="data1/tooltips/fachada02.jpg" alt="fachada-02"/>2</a>
</div></div><span class="wsl"><a href="http://wowslider.com/vw">slider wordpress</a> by WOWSlider.com v5.6</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>